-- THIS WILL CREATE A DATABASE FOR US
CREATE DATABASE DB_JOB;

-- THIS WILL SWITCH BETWEEN DATABASES 
USE DB_JOB;

-- THIS WILL CREATE A TABLE FOR US
CREATE TABLE TBL_USER(
    userid int(11) primary key,
    name varchar(50),
    qualification varchar (50),
    experience int(11)
);


-- THIS WILL SINGLE-LINE INSERT INTO YOUR TABLE 
INSERT INTO TBL_USER VALUES (1, 'Nkechi', 'Bsc', 3);

-- THIS WILL MULTI-LINE INSERT INTO YOUR TABLE 
INSERT INTO TBL_USER VALUES (1, 'Nkechi', 'Bsc', 3),
(2, 'Abdulai', 'Msc', 5),
(3, 'Dasola', 'Pg/Dip', 7),
(4, 'Ibrahim', 'Hnd', 9);

-- THIS WILL READ ALL INFORMATION FROM YOUR TABLE
SELECT * FROM TBL_USER;

-- THIS WILL UPDATE ONE ROW BY THE ID 
UPDATE TBL_USER
SET experience = 10
WHERE userid = 1;

--THIS WILL DELETE A RECORD FROM A TABLE 
DELETE FROM TBL_USER
WHERE userid = 4;